[postgres]
dbname= "football"
user= "postgres"
password= "password"
host= "localhost.com"
port= 5432

[db_config]
dbname = "football"
user = "root"
password = "Dikmosh_06"
host = "localhost"
port = 3306